# Generated by Django 4.1.1 on 2022-10-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='length',
        ),
    ]
